version: "3.9"
services:
  web:
    build: ./web
    ports:
      - "80:5000"

  database:
    build: ./database
    ports:
      - 5435:5432
    environment:
      - POSTGRESS_USER=postgres
      - POSTGRESS_PASSWORD=postgres

  api:
    build: ./db/api
    image: python:3.10-alpine
    ports:
      - 3000:3000
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@database:5432/database
    volumes:
      - './db/api/:/code'

volumes:
  db_volume:
  db:
    driver: local